@endpoint=http://localhost:8085
@test_user_token=CfDJ8B8vgv0iBzVKiQwDxVjDVRNf5p4MsvAZYjXf1fsbaNZys69DnRNXr5jQ_Al8ByWAwW0W9JcitMs4_u0LJh8NotqYjWTyTkwjCHK-OPBykUubNkLjD70OZCYE7B-g6skDDhvTFogP06jtf5BmDwUu4q3g6woi-wlUD51QlxsVmn0A
@admin_token=CfDJ8B8vgv0iBzVKiQwDxVjDVRPwDk0IIWilQHPYHoDcIZuBab67pG2vbLX88TJ88vGstOJDSIUj5lBLjMJAW7jVmkBKJ4WMpjKrSxOiyvKgM3PHE7FyjzexyT3IxnF4otr6BLMRpvdaKjor8Op13b5pN8nDx3Z1XAlJCcF6a8Rc3E5q

### Get user list

GET {{endpoint}}/api/v1/users HTTP/1.1
Authorization: Bearer {{test_user_token}}

### Get user list / privileged

GET {{endpoint}}/api/v1/users HTTP/1.1
Authorization: Bearer {{admin_token}}

### Get user by id

GET {{endpoint}}/api/v1/users/111 HTTP/1.1
Authorization: Bearer {{admin_token}}

### Get user by id (non-existing)

GET {{endpoint}}/api/v1/users/1 HTTP/1.1
Authorization: Bearer {{admin_token}}

### Get user data by id

GET {{endpoint}}/api/v1/users/111/data HTTP/1.1
Authorization: Bearer {{admin_token}}

### Get user data by data

GET {{endpoint}}/api/v1/users/111/data/2019-10-20 HTTP/1.1
Authorization: Bearer {{admin_token}}

### Add new calories

POST {{endpoint}}/api/v1/users/111/data/2019-10-20 HTTP/1.1
Authorization: Bearer {{admin_token}}
content-type: application/json

{
    "rtime": "12:25",
    "meal": "Fish",
    "amount": 125.0
}

### Update data

PUT {{endpoint}}/api/v1/users/111/data/2019-10-20/2 HTTP/1.1
Authorization: Bearer {{admin_token}}
content-type: application/json

{
    "rtime": "12:22",
    "meal": "Apple",
    "amount": 2.0
}

### Update partial

PUT {{endpoint}}/api/v1/users/111/data/2019-10-20/2 HTTP/1.1
Authorization: Bearer {{admin_token}}
content-type: application/json

{
    "rtime": "12:23"
}

### Delete data

DELETE {{endpoint}}/api/v1/users/111/data/2019-10-20/11 HTTP/1.1
Authorization: Bearer {{admin_token}}

### Authentication (login as admin)

POST {{endpoint}}/api/login HTTP/1.1
content-type: application/json

{
    "login": "admin",
    "pwd": "admin"
}

### Login as test

POST {{endpoint}}/api/login HTTP/1.1
content-type: application/json

{
    "login": "test",
    "pwd": "test"
}

### Verify authorization (admin user)

GET {{endpoint}}/api/who HTTP/1.1
Authorization: Bearer {{admin_token}}

### Retrieve info about logged in user

GET {{endpoint}}/api/v1/me HTTP/1.1
Authorization: Bearer {{test_user_token}}

### Request mine data

GET {{endpoint}}/api/v1/data HTTP/1.1
Authorization: Bearer {{test_user_token}}

### Request mine data

GET {{endpoint}}/api/v1/data/2019-10-21 HTTP/1.1
Authorization: Bearer {{test_user_token}}

### Post mine

POST {{endpoint}}/api/v1/data/2019-10-21 HTTP/1.1
Authorization: Bearer {{test_user_token}}
content-type: application/json

{
    "rtime": "12:10",
    "meal": "Chicken",
    "amount": 50.0
}

### Delete mine data

DELETE {{endpoint}}/api/v1/data/2019-10-20/12 HTTP/1.1
Authorization: Bearer {{test_user_token}}

### Read settings

GET {{endpoint}}/api/v1/settings HTTP/1.1
Authorization: Bearer {{test_user_token}}

### Update settings

PUT {{endpoint}}/api/v1/settings HTTP/1.1
Authorization: Bearer {{test_user_token}}
content-type: application/json

{
    "targetCalories": 480.2
}